'use client';

import React, { useEffect, useState, useMemo } from 'react';
import Navbar from '../components/navbar';
import { getMarketplaceListings } from '../actions';
import {
  Search,
  Zap,
  Code2,
  Copy,
  CheckCheck,
  ExternalLink,
  Database,
  Cpu,
  ShieldCheck,
  FileText,
  Globe,
  Star,
} from 'lucide-react';

type Listing = Awaited<ReturnType<typeof getMarketplaceListings>>[number];

const CATEGORIES = ['All', 'PriceData', 'Compute', 'Compliance', 'Document', 'Other'] as const;

const CATEGORY_META: Record<string, { icon: React.ElementType; color: string; label: string }> = {
  All: { icon: Globe, color: 'text-zinc-400', label: 'All APIs' },
  PriceData: { icon: Database, color: 'text-indigo-400', label: 'Price Data' },
  Compute: { icon: Cpu, color: 'text-violet-400', label: 'Compute' },
  Compliance: { icon: ShieldCheck, color: 'text-emerald-400', label: 'Compliance' },
  Document: { icon: FileText, color: 'text-amber-400', label: 'Documents' },
  Other: { icon: Globe, color: 'text-zinc-400', label: 'Other' },
};

const TIER_RANK: Record<string, number> = { Elite: 4, Trusted: 3, Established: 2, New: 1 };
const TIER_STYLE: Record<string, string> = {
  Elite: 'bg-indigo-500/10 text-indigo-300 border-indigo-500/30',
  Trusted: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
  Established: 'bg-blue-500/10 text-blue-300 border-blue-500/30',
  New: 'bg-zinc-500/10 text-zinc-300 border-zinc-500/30',
};

function buildSnippet(listing: Listing, lang: 'python' | 'node'): string {
  const price = (Number(listing.price_motes) / 1e9).toFixed(4);
  if (lang === 'python') {
    return `import requests, json

# AgentPay x402 payment header (generated by the MCP server in production)
payment_header = json.dumps({
    "protocol": "x402",
    "version": "1",
    "scheme": "casper-cspr",
    "network": "casper-test",
    "payload": {
        "from":         "<agent_account_hash>",
        "to":           "${listing.provider_wallet}",
        "amount":       "${listing.price_motes}",  # ${price} CSPR
        "listing_id":   ${listing.listing_id},
        "nonce":        "<uuid_v4>",
        "expires_at":   <unix_timestamp>,
        "facilitator_url": "http://localhost:3001"
    },
    "signature": "<ed25519_signature>"
})

resp = requests.get(
    "${listing.endpoint_url}",
    headers={"X-Payment": payment_header}
)
print(resp.json())`;
  }
  return `import fetch from 'node-fetch';

// AgentPay x402 payment header (generated by the MCP server in production)
const paymentHeader = JSON.stringify({
  protocol: 'x402',
  version: '1',
  scheme: 'casper-cspr',
  network: 'casper-test',
  payload: {
    from:            '<agent_account_hash>',
    to:              '${listing.provider_wallet}',
    amount:          '${listing.price_motes}',  // ${price} CSPR
    listing_id:      ${listing.listing_id},
    nonce:           '<uuid_v4>',
    expires_at:      Math.floor(Date.now() / 1000) + 300,
    facilitator_url: 'http://localhost:3001',
  },
  signature: '<ed25519_signature>',
});

const resp = await fetch('${listing.endpoint_url}', {
  headers: { 'X-Payment': paymentHeader },
});
console.log(await resp.json());`;
}

export default function MarketplacePage() {
  const [listings, setListings] = useState<Listing[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [selected, setSelected] = useState<Listing | null>(null);
  const [snippetLang, setSnippetLang] = useState<'python' | 'node'>('node');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    getMarketplaceListings()
      .then(setListings)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return listings
      .filter((l) => activeCategory === 'All' || l.category === activeCategory)
      .filter(
        (l) =>
          !search ||
          l.name.toLowerCase().includes(search.toLowerCase()) ||
          (l.description ?? '').toLowerCase().includes(search.toLowerCase()),
      )
      .sort((a, b) => (TIER_RANK[b.reputation_tier] ?? 1) - (TIER_RANK[a.reputation_tier] ?? 1));
  }, [listings, activeCategory, search]);

  const formatMotes = (m: string | number) => {
    try {
      return (Number(BigInt(m.toString())) / 1e9).toLocaleString(undefined, {
        minimumFractionDigits: 4,
        maximumFractionDigits: 4,
      });
    } catch {
      return '0.0000';
    }
  };

  const handleCopy = () => {
    if (!selected) return;
    navigator.clipboard.writeText(buildSnippet(selected, snippetLang));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col min-h-screen bg-[#0b0b0f]">
      <Navbar />

      <main className="flex-grow mx-auto max-w-7xl w-full px-4 sm:px-6 lg:px-8 py-10">
        {/* Page Header */}
        <div className="mb-10">
          <span className="text-xs font-semibold text-violet-400 uppercase tracking-widest">
            Marketplace
          </span>
          <h1 className="text-3xl font-bold tracking-tight text-white mt-1">API Marketplace</h1>
          <p className="mt-1 text-sm text-zinc-500 max-w-2xl">
            Browse registered paid APIs. AI agents use the MCP server to discover and call these
            autonomously with x402 micropayments on Casper.
          </p>
        </div>

        {/* Search + Filter Row */}
        <div className="flex flex-col md:flex-row gap-4 mb-8">
          <div className="relative flex-1">
            <Search
              size={15}
              className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500 pointer-events-none"
            />
            <input
              id="marketplace-search"
              type="text"
              placeholder="Search APIs by name or description…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full rounded-xl border border-white/10 bg-zinc-950/40 pl-10 pr-4 py-3 text-sm text-white placeholder-zinc-600 focus:border-violet-500 focus:outline-none focus:ring-1 focus:ring-violet-500"
            />
          </div>

          {/* Category tabs */}
          <div className="flex items-center gap-1.5 flex-wrap">
            {CATEGORIES.map((cat) => {
              const meta = CATEGORY_META[cat];
              const Icon = meta.icon;
              const isActive = activeCategory === cat;
              return (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={`flex items-center gap-1.5 rounded-xl px-3.5 py-2.5 text-xs font-semibold transition-all border ${
                    isActive
                      ? 'bg-violet-600/15 text-violet-300 border-violet-500/30'
                      : 'border-white/8 bg-white/3 text-zinc-400 hover:text-zinc-200 hover:border-white/15'
                  }`}
                >
                  <Icon size={12} className={isActive ? 'text-violet-400' : meta.color} />
                  {meta.label}
                </button>
              );
            })}
          </div>
        </div>

        {/* Main content: listing grid + code panel */}
        <div className={`grid gap-8 ${selected ? 'lg:grid-cols-5' : 'lg:grid-cols-3'}`}>
          {/* Listing Grid */}
          <div
            className={`${selected ? 'lg:col-span-3' : 'lg:col-span-3'} grid gap-4 auto-rows-max ${
              !selected ? 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3' : 'grid-cols-1 sm:grid-cols-2'
            }`}
          >
            {loading
              ? Array.from({ length: 6 }).map((_, i) => (
                  <div
                    key={i}
                    className="glass-panel rounded-2xl border-white/5 h-52 animate-pulse bg-zinc-900/20"
                  />
                ))
              : filtered.length === 0
              ? (
                  <div className="col-span-full text-center py-24 px-4">
                    <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-zinc-900 text-zinc-500 mx-auto mb-5 border border-white/5">
                      <Search size={22} />
                    </div>
                    <h3 className="text-white font-bold text-lg">No APIs found</h3>
                    <p className="mt-2 text-sm text-zinc-500 max-w-xs mx-auto">
                      Try a different search term or category, or run the demo setup script to
                      register the mock providers.
                    </p>
                  </div>
                )
              : filtered.map((listing) => {
                  const meta = CATEGORY_META[listing.category ?? 'Other'] ?? CATEGORY_META.Other;
                  const Icon = meta.icon;
                  const isSelected = selected?.listing_id === listing.listing_id;
                  return (
                    <button
                      key={listing.listing_id}
                      onClick={() => setSelected(isSelected ? null : listing)}
                      className={`text-left glass-panel rounded-2xl border transition-all duration-200 p-5 flex flex-col gap-3 ${
                        isSelected
                          ? 'border-violet-500/40 bg-violet-900/10 shadow-lg shadow-violet-500/10'
                          : 'border-white/5 hover:border-violet-500/20 hover:bg-white/[0.02]'
                      }`}
                    >
                      {/* Top row: category + tier badge */}
                      <div className="flex items-center justify-between gap-2">
                        <span
                          className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-bold bg-zinc-900/80 border border-white/5 ${meta.color}`}
                        >
                          <Icon size={9} />
                          {listing.category}
                        </span>
                        <span
                          className={`inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full border ${
                            TIER_STYLE[listing.reputation_tier] ?? TIER_STYLE.New
                          }`}
                        >
                          <Star size={8} />
                          {listing.reputation_tier}
                        </span>
                      </div>

                      {/* Name + description */}
                      <div>
                        <h3 className="font-bold text-white text-sm leading-tight">{listing.name}</h3>
                        <p className="mt-1.5 text-zinc-400 text-xs leading-relaxed line-clamp-2">
                          {listing.description}
                        </p>
                      </div>

                      {/* Price + CTA */}
                      <div className="mt-auto flex items-center justify-between pt-3 border-t border-white/5">
                        <div>
                          <span className="text-[10px] text-zinc-500">Cost per call</span>
                          <p className="text-emerald-400 font-black font-mono text-sm">
                            {formatMotes(listing.price_motes)} CSPR
                          </p>
                        </div>
                        <span
                          className={`text-[10px] font-semibold px-2.5 py-1 rounded-lg border ${
                            isSelected
                              ? 'bg-violet-600/20 text-violet-300 border-violet-500/30'
                              : 'bg-white/5 text-zinc-400 border-white/10'
                          }`}
                        >
                          {isSelected ? 'View code ↑' : 'Integration →'}
                        </span>
                      </div>
                    </button>
                  );
                })}
          </div>

          {/* Code Snippet Panel */}
          {selected && (
            <div className="lg:col-span-2">
              <div className="glass-panel rounded-2xl border-white/5 bg-[#121218]/70 overflow-hidden sticky top-24">
                {/* Panel header */}
                <div className="flex items-center justify-between px-5 py-4 border-b border-white/5">
                  <div className="flex items-center gap-2">
                    <Code2 size={15} className="text-violet-400" />
                    <span className="text-sm font-bold text-white">Integration Code</span>
                  </div>
                  <div className="flex items-center gap-2">
                    {/* Lang switcher */}
                    <div className="flex rounded-lg border border-white/10 overflow-hidden text-[10px] font-semibold">
                      <button
                        onClick={() => setSnippetLang('node')}
                        className={`px-3 py-1.5 transition-colors ${
                          snippetLang === 'node'
                            ? 'bg-violet-600/20 text-violet-300'
                            : 'bg-transparent text-zinc-500 hover:text-zinc-300'
                        }`}
                      >
                        Node.js
                      </button>
                      <button
                        onClick={() => setSnippetLang('python')}
                        className={`px-3 py-1.5 transition-colors ${
                          snippetLang === 'python'
                            ? 'bg-violet-600/20 text-violet-300'
                            : 'bg-transparent text-zinc-500 hover:text-zinc-300'
                        }`}
                      >
                        Python
                      </button>
                    </div>
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-[10px] font-semibold text-zinc-400 hover:bg-white/10 hover:text-zinc-200 transition-colors"
                    >
                      {copied ? (
                        <>
                          <CheckCheck size={12} className="text-emerald-400" /> Copied!
                        </>
                      ) : (
                        <>
                          <Copy size={12} /> Copy
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* Listing quick summary */}
                <div className="px-5 py-3 border-b border-white/5 bg-black/20 flex flex-wrap gap-4 text-[10px] font-mono">
                  <div>
                    <span className="text-zinc-500 uppercase tracking-wider">Listing ID </span>
                    <span className="text-violet-300">#{selected.listing_id}</span>
                  </div>
                  <div>
                    <span className="text-zinc-500 uppercase tracking-wider">Price </span>
                    <span className="text-emerald-300">{formatMotes(selected.price_motes)} CSPR</span>
                  </div>
                  <div>
                    <span className="text-zinc-500 uppercase tracking-wider">Tier </span>
                    <span className="text-indigo-300">{selected.reputation_tier}</span>
                  </div>
                  <a
                    href={`https://testnet.cspr.live`}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-1 text-zinc-500 hover:text-zinc-300 transition-colors"
                  >
                    <ExternalLink size={10} /> Explorer
                  </a>
                </div>

                {/* Code block */}
                <pre className="overflow-auto p-5 text-[11px] leading-relaxed text-zinc-300 bg-transparent max-h-[28rem] font-mono">
                  <code>{buildSnippet(selected, snippetLang)}</code>
                </pre>

                {/* MCP tip */}
                <div className="px-5 py-4 border-t border-white/5 bg-violet-900/5">
                  <p className="text-[10px] text-zinc-500 leading-relaxed">
                    <span className="text-violet-400 font-semibold">Tip:</span> In production, AI agents
                    call this API autonomously via the AgentPay MCP server — the payment header is
                    constructed and signed automatically without any human involvement.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Stats bar */}
        {!loading && (
          <div className="mt-10 pt-8 border-t border-white/5 flex flex-wrap items-center gap-6 text-xs text-zinc-500">
            <span>
              <span className="text-white font-bold">{listings.length}</span> total APIs registered
            </span>
            <span>
              <span className="text-white font-bold">{filtered.length}</span> matching your filters
            </span>
            <span>
              <span className="text-white font-bold">
                {listings.filter((l) => l.reputation_tier === 'Elite').length}
              </span>{' '}
              Elite tier
            </span>
            <span className="ml-auto">
              <Zap size={11} className="inline mr-1 text-violet-400" />
              All prices settled on Casper Testnet
            </span>
          </div>
        )}
      </main>
    </div>
  );
}
